### ISSUE TITLE
Fix bug in odd score bonus points

### ISSUE THREAD

**Issue by americast** [americast/Snakes#1]
When score is odd, the snake is unable to intake the bonus.

**Comment by cyberfreak5725** [comment]
I played the game and saw that, it was taking intaking bonus when score was odd. It was not showing bonus food while the score was odd(by observation)

**Comment by americast** [comment]
@cyberfreak5725 The bonus appears when you have a score as a multiple of four. But if you eat a normal food, and not the bonus, when a bonus is available, it renders the bonus "inedible" at times.

**Comment by hrishabh23** [comment]
@americast I think the problem is not related to odd score.
We check that if the head of the snake touches food particle, then it's considered eaten. In function checkFood() and checkBonus():
```
 if (arrx[0]==i && arry[0]==j)
       {flag=1; break;}
```
But at higher levels, the snake goes through the particle without coordinates of head going inside the particle. Which happens due to this, in the while(1) loop:
```
for (int i=1; i<=8+(1.5*level);i++)
        setPos();
```
Fixing code in above two functions (checkFood() and checkBonus()), solves the problem.
